### ISSUE TITLE
大佬 colab装依赖时fairseq报错

### ISSUE THREAD

**Issue by Mazinrenown** [Plutoisy/so-vits-svc#2]
Building wheel for pyworld (setup.py) ... done
  Created wheel for pyworld: filename=pyworld-0.2.12-cp39-cp39-linux_x86_64.whl size=894376 sha256=84c8ed9ba7fe59d734777a8be48b1d9261a9a8d9216f185583b6a3333107502f
  Stored in directory: /root/.cache/pip/wheels/81/fd/3d/ef32d5bbaef47055511340fc89f361c397770c65c3012f9945
  error: subprocess-exited-with-error
  
  × Building wheel for fairseq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for fairseq (pyproject.toml) ... error
  ERROR: Failed building wheel for fairseq
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141231 sha256=0c77c1500f70ace1c81fb7faa7f8a27910ebdc3a7e89ddeec066c5a6a7420bc3
  Stored in directory: /root/.cache/pip/wheels/42/3c/ae/14db087e6018de74810afe32eb6ac890ef9c68ba19b00db97a
  Building wheel for ffmpy (setup.py) ... done
  Created wheel for ffmpy: filename=ffmpy-0.3.0-py3-none-any.whl size=4711 sha256=a7732a29b39075248fc2df40f86ba4c7867d0cae3f85e2d99fc265c81d7800d1
  Stored in directory: /root/.cache/pip/wheels/91/e2/96/f676aa08bfd789328c6576cd0f1fde4a3d686703bb0c247697
Successfully built pyworld antlr4-python3-runtime ffmpy
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

终于这个报错从我的电脑上传染到了colab上（

**Comment by Plutoisy** [comment]
我用着也报错，感觉像colab的问题（以前好像还没这个问题），不过我在windows环境下的pc上跑没问题，在pc上跑完数据集预处理后传给colab就行了

**Comment by Mazinrenown** [comment]
> 我用着也报错，感觉像colab的问题（以前好像还没这个问题），不过我在windows环境下的pc上跑没问题，在pc上跑完数据集预处理后传给colab就行了

大草 那我试试pc上再下个新的python 看看再装依赖会怎么样了（
有预处理即使这玩意报错也能接着训练吗（

**Comment by Nate-rui** [comment]
把python版本换成3.8即可 推测是colab的问题

**Comment by JameT5123** [comment]
> 把python版本换成3.8即可 推测是colab的问题

colab上要如何操作才能换成3.8呀

**Comment by Nate-rui** [comment]
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local

**Comment by JameT5123** [comment]
> 

是将 #@title 安装依赖 下方的代码全部替换成这个嘛

**Comment by JameT5123** [comment]
> !wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh !chmod +x mini.sh !bash ./mini.sh -b -f -p /usr/local

是将 #@title 安装依赖 下方的代码全部替换成这个吗

**Comment by Mazinrenown** [comment]
> > !wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh !chmod +x mini.sh !bash ./mini.sh -b -f -p /usr/local
> 
> 是将 #@title 安装依赖 下方的代码全部替换成这个吗

我猜是在前面先给一个框运行这个 把py版本换了再执行下载requirement……

**Comment by Plutoisy** [comment]
colab脚本更新了，应该没问题了。python版本改成了Miniconda3-py39_4.11.0-Linux-x86_64，感谢Summ3rM0，py38也有点问题，py39没什么问题了，有问题可以继续在这个issue下提。

**Comment by Mazinrenown** [comment]
> colab脚本更新了，应该没问题了。python版本改成了Miniconda3-py39_4.11.0-Linux-x86_64，感谢Summ3rM0，py38也有点问题，py39没什么问题了，有问题可以继续在这个issue下提。

生成heburt时报error
[502]
Loading hubert for content...
load model(s) from hubert/checkpoint_best_legacy_500.pt
INFO:fairseq.tasks.text_to_speech:Please install tensorboardX: pip install tensorboardX
INFO:fairseq.tasks.hubert_pretraining:current directory is /content/so-vits-svc
INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Loaded hubert.
  0% 0/502 [00:07<?, ?it/s]
Process Process-1:
Traceback (most recent call last):
  File "__init__.pxd", line 1035, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch
    process_one(filename, hmodel)
  File "/content/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one
    f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length)
  File "/content/so-vits-svc/utils.py", line 156, in compute_f0_dio
    import pyworld
  File "/usr/local/lib/python3.9/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld
  File "__init__.pxd", line 1037, in numpy.import_array
ImportError: numpy.core.multiarray failed to import


追溯到再前面的话装依赖时有个warning
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: The following packages were previously imported in this runtime:
  [cycler,dateutil,google,kiwisolver]
You must restart the runtime in order to use newly installed versions.

**Comment by Plutoisy** [comment]
在进行数据集预处理时使用1.23.5的numpy
!pip uninstall numpy
!pip install numpy==1.23.5
进行训练前再降级为1.22.0
!pip uninstall numpy
!pip install numpy==1.22.0
colab脚本已更新

**Comment by Nate-rui** [comment]
其实训练时出现的numpy版本警告可以无视 对训练没有影响

**Comment by Nate-rui** [comment]
而且据我测试 python3.8不会出问题 反而python3.9会报错 依赖装不上
